import {DashboardLayout} from "@/components/dashboard-layout";
import {Metadata} from "next";
import {ReactNode} from "react";

export const metadata: Metadata = {
	title: "Users",
	description: "Generated by create next app",
};

export default function UserLayout({children}: {children: ReactNode}) {
	return <DashboardLayout>{children}</DashboardLayout>;
}
